#!/bin/bash
#Purpose: Scripts changes directory to entered directory without entering full path
#		  No need to type the full path
#Version: 1.0
#Created Date:  Fri Nov 18 07:45:32 AM GMT 2022
#Modified Date:
#Author: Abdul-Fatahu Hardi
# START #
dir=$1

case "$dir" in
	"home")		cd /home/at-tawlib
				;;
	"desktop")	cd /home/at-tawlib/Desktop
				;;
	"alx")		cd /home/at-tawlib/Desktop/ALXSE
				;;
	"python")	cd /home/at-tawlib/Desktop/Python3
				;;
	*) echo		"Directory not available"
				;;
esac
# END #
